"""333444df

Revision ID: 74f2773a5a1c
Revises: 168097ddf9b8
Create Date: 2023-07-28 00:01:02.027084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74f2773a5a1c'
down_revision = '168097ddf9b8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
